name: fit_log
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # 🧠 State Management
  flutter_riverpod: ^2.4.0

  # 📦 Local Data Persistence
  path_provider: ^2.1.1
  excel: ^2.0.9 # To read/write .xlsx files
  file_picker: ^10.1.2
  permission_handler: ^11.3.0

  # 🧊 Code Generation / Model Helpers
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # 📱 UI Essentials
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.0
  flutter_slidable: ^3.0.0
  intl: ^0.19.0
  table_calendar: ^3.0.9

  # 📷 Image Picker (for guide images)
  image_picker: ^1.0.7

  # 🧭 Navigation (optional but clean)
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.0
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
